--DATES

SELECT GETDATE()

SELECT GETDATE() - 2

--DATEPART

SELECT DATEPART(yyyy, GETDATE())

SELECT DATEPART(dd, GETDATE())

SELECT DATEPART(mm, GETDATE())

--DATEADD

SELECT DATEADD(day, 4, GETDATE())
SELECT DATEADD(month, 4, GETDATE())
SELECT DATEADD(year, 4, GETDATE())

--DATEDIFF
SELECT DATEDIFF(day, '6/1/2015', GETDATE())
SELECT DATEDIFF(month, '6/1/2015', GETDATE())

SELECT DATEDIFF(month, '4/1/2015', GETDATE())

SELECT DATEDIFF(year, '6/1/2014', GETDATE())

--QUERY
SELECT top 10 * FROM [AdventureWorks2012].[Production].[WorkOrder]

SELECT WorkOrderID, ProductID, StartDate, EndDate,  DATEDIFF(day, StartDate, EndDate)
FROM [AdventureWorks2012].[Production].[WorkOrder]

--GET THE FIRST DAY OF THIS MONTH
SELECT (DATEADD(dd, -(DATEPART(day, GETDATE()) - 1), GETDATE()))