---FUNCTIONS
SELECT * FROM MYSALARY

--AGGREGATE FUNCTIONS
SELECT AVG(SALARY) FROM MYSALARY

SELECT COUNT(SALARY) FROM MYSALARY

SELECT COUNT(*) FROM MYSALARY

SELECT SUM(SALARY) FROM MYSALARY

SELECT MIN(SALARY) FROM MYSALARY

SELECT MAX(SALARY) FROM MYSALARY


--STRING FUNCTIONS
SELECT * FROM MYORDER

SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME, ' ' , ORDERNAME) AS CONCATENATEDTEXT FROM MYORDER

--RAND()
SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME, ' ' , RAND(5)) AS CONCATENATEDTEXT FROM MYORDER

--LEFT
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 5) FROM MYORDER

--RIGHT
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 5) FROM MYORDER

--SUBSTRING
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 2, 5) FROM MYORDER

--LOWERCASE
SELECT ORDERNUMBER, ORDERNAME, LOWER(ORDERNAME) FROM MYORDER

--LENGHT OF STRING
SELECT ORDERNUMBER, ORDERNAME, LEN(ORDERNAME) FROM MYORDER

SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME, 1)), LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME)))) FROM MYORDER

--TRIM
SELECT '   MyText    '
SELECT LEN('   MyText    ')

SELECT LTRIM('   MyText    ')
SELECT RTRIM('   MyText    ')
SELECT RTRIM(LTRIM('   MyText    '))
